version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: health
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '3306:3306'
  web:
    build: .
    restart: always
    volumes:
      - .:/var/www/html
    ports:
      - '8000:80'
    depends_on:
      - db
